FROM node:lts-alpine as builder

RUN mkdir app

WORKDIR /app

COPY tsconfig.json ./
COPY package*.json ./

RUN npm install
RUN npm install --save-dev typescript

COPY src ./src
COPY public ./public

RUN npm run build

FROM node:lts-alpine

RUN mkdir app

WORKDIR /app

COPY --from=builder /app/build ./app/build

COPY package*.json ./

RUN npm install

CMD npx serve app/build